server:
    port: 8080

management:
    health:
        diskspace:
            enabled: false
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: health, env
            base-path: '/'

spring:
    h2:
        console:
            enabled: 'true'
    datasource:
        url: jdbc:h2:mem:mydb
        username: sa
        password: password
        driverClassName: org.h2.Driver
    jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
        show-sql: 'true'
        hibernate:
            ddl-auto: update
        defer-datasource-initialization: true
springdoc:
    packagesToScan: com.uepb.lufh.avalia.entrypoint.controller
    pathsToMatch: /**
    swagger-ui:
        disable-swagger-default-url: true
        doc-expansion: none
        tagsSorter: alpha