server:
    port: 8080

management:
    health:
        diskspace:
            enabled: false
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: health, env
            base-path: '/'

spring:
    jackson:
        date-format: com.uepb.lufh.avalia.configuration.RFC3339DateFormat
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: 'false'