INSERT INTO customer (customer_id, cpf_cnpj, customer_name, email, phone_number)
VALUES (1, '44443085000158',  'João da Silva', 'joao.silva@example.com', '+55 11 99999-9999');

INSERT INTO product (product_id, product_name, manufacturer_name, completion_level, product_type, product_class)
VALUES (1, 'Notebook XPTO', 'Acme Inc.',  'Alfa', 'Eletrônico', 'Class I');

INSERT INTO question (question_class, product_type, base_question, detailed_question ) VALUES
	('Aesthetic and minimalist design', 'Software', 'Is it designed minimal?', ''),
	('Aesthetic and minimalist design', '', 'Is it designed minimal?', '"Is only (and all) information, essential to decision making, displayed on the screen?"'),
	('Aesthetic and minimalist design', 'Software', 'Is it designed minimal?', '"If visual elements (such as arrows or lines) are used, do they provide extra information?"'),
	('Aesthetic and minimalist design', 'Software', 'Is it designed minimal?', '"Are there enough function keys to support functionality, but not so many that scanning and finding are difficult?"'),
	('Aesthetic and minimalist design', 'Software', 'Is the design consistent?', ''),
	('Aesthetic and minimalist design', 'Software', 'Is the design consistent?', 'Do the colors used in the system bear semantic information?'),
	('Aesthetic and minimalist design', 'Software', 'Is the design consistent?', 'Does the semantic information of colors remain the same throughout the whole system?'),
	('Aesthetic and minimalist design', 'Software', 'Is the design consistent?', 'Do the selected colors correspond to common expectations about color codes?'),
	('Aesthetic and minimalist design', 'Software', '', '"Do menu instructions, prompts, and error messages appear in the same place(s) on each other?"'),
	('Aesthetic and minimalist design', 'Software', 'Is the design consistent?', 'Are all icons in a set visually and conceptually distinct?'),
	('Aesthetic and minimalist design', 'Software', 'Is the design consistent?', 'Does each icon stand out from its background?'),
	('Aesthetic and minimalist design', 'Software', 'Is the design consistent?', 'Are data-entry fields for a finite set of options implemented as pop-up or pull-down menus?'),
	('Aesthetic and minimalist design', 'Hardware', 'Is it designed minimal?', ''),
	('Aesthetic and minimalist design', 'Hardware', 'Is it designed minimal?', '"Is only (and all) information, essential to decision making, displayed on the screen?"'),
	('Aesthetic and minimalist design', 'Hardware', 'Is it designed minimal?', '"If visual elements (such as arrows or lines) are used, do they provide extra information?"'),
	('Aesthetic and minimalist design', 'Hardware', 'Is it designed minimal?', '"Are there enough function keys to support functionality, but not so many that scanning and finding are difficult?"'),
	('Aesthetic and minimalist design', 'Hardware', 'Is the design consistent?', ''),
	('Aesthetic and minimalist design', 'Hardware', 'Is the design consistent?', 'Do the colors used in the system bear semantic information?'),
	('Aesthetic and minimalist design', 'Hardware', 'Is the design consistent?', 'Does the semantic information of colors remain the same throughout the whole system?'),
	('Aesthetic and minimalist design', 'Hardware', 'Is the design consistent?', 'Do the selected colors correspond to common expectations about color codes?'),
	('Aesthetic and minimalist design', 'Hardware', '', '"Do menu instructions, prompts, and error messages appear in the same place(s) on each other?"'),
	('Aesthetic and minimalist design', 'Hardware', 'Is the design consistent?', 'Are all icons in a set visually and conceptually distinct?'),
	('Aesthetic and minimalist design', 'Hardware', 'Is the design consistent?', 'Does each icon stand out from its background?'),
	('Aesthetic and minimalist design', 'Hardware', 'Is the design consistent?', 'Are data-entry fields for a finite set of options implemented as pop-up or pull-down menus?'),
	('Consistency and standards', 'Software', 'Is terminology of each UI element and each content used in a consistent way?', ''),
	('Consistency and standards', 'Software', 'Is terminology of each UI element and each content used in a consistent way?', '"Is terminology consistent and organized consistently (e.g., clinical reminders use What/When/Who structure)?"'),
	('Consistency and standards', 'Software', 'Is terminology of each UI element and each content used in a consistent way?', 'Are field labels consistent from one data entry screen to another?'),
	('Consistency and standards', 'Software', 'Is terminology of each UI element and each content used in a consistent way?', '"If the system has multipage data entry screens, do all pages have the same title?"'),
	('Consistency and standards', 'Software', 'Is terminology of each UI element and each content used in a consistent way?', '"Are menu choice names consistent, both within each menu and across the system, in grammatical style and terminology?"'),
	('Consistency and standards', 'Software', 'Is terminology of each UI element and each content used in a consistent way?', 'Is the structure of a data entry value consistent from screen to screen?'),
	('Consistency and standards', 'Software', 'Is terminology of each UI element and each content used in a consistent way?', 'Are user actions named consistently across all prompts in the system?'),
	('Consistency and standards', 'Software', 'Is terminology of each UI element and each content used in a consistent way?', 'Are system objects named consistently across all prompts in the system?'),
	('Consistency and standards', 'Software', 'Is terminology of each UI element and each content used in a consistent way?', 'Is the same measurement system used consistently?'),
	('Consistency and standards', 'Software', 'Is terminology of each UI element and each content used in a consistent way?', 'Are the same measurement units used consistently?'),
	('Consistency and standards', 'Software', 'Does the system behave in a consistent way?', ''),
	('Consistency and standards', 'Software', 'Does the system behave in a consistent way?', '"Are function key assignments consistent across screens, subsystems, and related products?"'),
	('Consistency and standards', 'Software', 'Does the system behave in a consistent way?', '"Are commands used the same way, and do they mean the same thing, in all parts of the system?"'),
	('Consistency and standards', 'Software', 'Does the system behave in a consistent way?', 'Is the method for moving the cursor to the next or previous field consistent throughout the system?'),
	('Consistency and standards', 'Software', 'Does the system behave in a consistent way?', 'Do the same user actions on different dialog steps always lead to the same effects?'),
	('Consistency and standards', 'Software', 'Does the system behave in a consistent way?', 'Are similar interactions executed in a similar way?'),
	('Consistency and standards', 'Hardware', 'Is terminology of each UI element and each content used in a consistent way?', ''),
	('Consistency and standards', 'Hardware', 'Is terminology of each UI element and each content used in a consistent way?', '"Is terminology consistent and organized consistently (e.g., clinical reminders use What/When/Who structure)?"'),
	('Consistency and standards', 'Hardware', 'Is terminology of each UI element and each content used in a consistent way?', 'Are field labels consistent from one data entry screen to another?'),
	('Consistency and standards', 'Hardware', 'Is terminology of each UI element and each content used in a consistent way?', '"If the system has multipage data entry screens, do all pages have the same title?"'),
	('Consistency and standards', 'Hardware', 'Is terminology of each UI element and each content used in a consistent way?', '"Are menu choice names consistent, both within each menu and across the system, in grammatical style and terminology?"'),
	('Consistency and standards', 'Hardware', 'Is terminology of each UI element and each content used in a consistent way?', 'Is the structure of a data entry value consistent from screen to screen?'),
	('Consistency and standards', 'Hardware', 'Is terminology of each UI element and each content used in a consistent way?', 'Are user actions named consistently across all prompts in the system?'),
	('Consistency and standards', 'Hardware', 'Is terminology of each UI element and each content used in a consistent way?', 'Are system objects named consistently across all prompts in the system?'),
	('Consistency and standards', 'Hardware', 'Is terminology of each UI element and each content used in a consistent way?', 'Is the same measurement system used consistently?'),
	('Consistency and standards', 'Hardware', 'Is terminology of each UI element and each content used in a consistent way?', 'Are the same measurement units used consistently?'),
	('Consistency and standards', 'Hardware', 'Does the system behave in a consistent way?', ''),
	('Consistency and standards', 'Hardware', 'Does the system behave in a consistent way?', '"Are function key assignments consistent across screens, subsystems, and related products?"'),
	('Consistency and standards', 'Hardware', 'Does the system behave in a consistent way?', '"Are commands used the same way, and do they mean the same thing, in all parts of the system?"'),
	('Consistency and standards', 'Hardware', 'Does the system behave in a consistent way?', 'Is the method for moving the cursor to the next or previous field consistent throughout the system?'),
	('Consistency and standards', 'Hardware', 'Does the system behave in a consistent way?', 'Do the same user actions on different dialog steps always lead to the same effects?'),
	('Consistency and standards', 'Hardware', 'Does the system behave in a consistent way?', 'Are similar interactions executed in a similar way?'),
	('Error prevention', 'Software', 'Does the system prevent users from making errors?', ''),
	('Error prevention', 'Software', 'Does the system prevent users from making errors?', 'Is transmitted information validated before it is processed?'),
	('Error prevention', 'Software', 'Does the system prevent users from making errors?', 'Does the system prevent wrong input (e.g. a value out of scale)?'),
	('Error prevention', 'Software', 'Does the system prevent users from making errors?', 'Has the use of qualifier keys been minimized?'),
	('Error prevention', 'Software', 'Does the system prevent users from making errors?', 'Does the system warn users if they are about to make a potentially serious error?'),
	('Error prevention', 'Software', 'Does the system prevent users from making errors?', 'Do data entry screens and dialog boxes indicate the number of character spaces available in a field?'),
	('Error prevention', 'Software', 'Does the system prevent users from making errors?', '"Are users prompted to confirm commands that have drastic, destructive consequences?"'),
	('Error prevention', 'Software', 'Does the system prevent users from making errors?', '"Are negative structures avoided (e.g., Do you not want to quit?)"'),
	('Error prevention', 'Hardware', 'Does the system prevent users from making errors?', ''),
	('Error prevention', 'Hardware', 'Does the system prevent users from making errors?', 'Is transmitted information validated before it is processed?'),
	('Error prevention', 'Hardware', 'Does the system prevent users from making errors?', 'Does the system prevent wrong input (e.g. a value out of scale)?'),
	('Error prevention', 'Hardware', 'Does the system prevent users from making errors?', 'Has the use of qualifier keys been minimized?'),
	('Error prevention', 'Hardware', 'Does the system prevent users from making errors?', 'Does the system warn users if they are about to make a potentially serious error?'),
	('Error prevention', 'Hardware', 'Does the system prevent users from making errors?', 'Do data entry screens and dialog boxes indicate the number of character spaces available in a field?'),
	('Error prevention', 'Hardware', 'Does the system prevent users from making errors?', '"Are users prompted to confirm commands that have drastic, destructive consequences?"'),
	('Error prevention', 'Hardware', 'Does the system prevent users from making errors?', '"Are negative structures avoided (e.g., Do you not want to quit?)"'),
	('Flexibility and efficiency of use', 'Software', 'Does the system provide shortcut functionality?', ''),
	('Flexibility and efficiency of use', 'Software', 'Does the system provide shortcut functionality?', 'Does the system provide shortcuts for the execution of the most frequently required functionality?'),
	('Flexibility and efficiency of use', 'Software', 'Does the system provide shortcut functionality?', 'Can the user define shortcuts by his own?'),
	('Flexibility and efficiency of use', 'Software', 'Can the user decide on using different input devices for performing the same action at each point in the dialog process?', ''),
	('Flexibility and efficiency of use', 'Software', 'Can the user decide on using different input devices for performing the same action at each point in the dialog process?', '"If menu lists are short (seven items or fewer), can users select an item by moving the cursor?"'),
	('Flexibility and efficiency of use', 'Software', 'Can the user decide on using different input devices for performing the same action at each point in the dialog process?', '"If the system uses a pointing device, do users have the option of either clicking on fields or using a keyboard shortcut?"'),
	('Flexibility and efficiency of use', 'Software', 'Can the user decide on using different input devices for performing the same action at each point in the dialog process?', '"In dialog boxes, do users have the option of either clicking directly on a dialog box option or using a keyboard shortcut?"'),
	('Flexibility and efficiency of use', 'Software', 'Can the user decide on using different input devices for performing the same action at each point in the dialog process?', '"Can expert users bypass nested dialog boxes with either type-ahead, user-defined macros, or keyboard shortcuts?"'),
	('Flexibility and efficiency of use', 'Software', 'Can the user decide on using different input devices for performing the same action at each point in the dialog process?', '"On data entry screens, do users have the option of either clicking directly on a field or using a keyboard shortcut?"'),
	('Flexibility and efficiency of use', 'Software', 'Can the user decide on using different input devices for performing the same action at each point in the dialog process?', '"On menus, do users have the option of either clicking directly on a menu item or using a keyboard shortcut?"'),
	('Flexibility and efficiency of use', 'Software', 'Can the user change the layout of the system according to his needs and preferences?', ''),
	('Flexibility and efficiency of use', 'Software', 'Can the user change the layout of the system according to his needs and preferences?', 'Is the size of graphics adaptable by the user?'),
	('Flexibility and efficiency of use', 'Software', 'Can the user change the layout of the system according to his needs and preferences?', 'Is the font size adaptable by the user for each UI element?'),
	('Flexibility and efficiency of use', 'Software', 'Can the user change the layout of the system according to his needs and preferences?', 'Are labels of objects and functions adaptable individually by the user?'),
	('Flexibility and efficiency of use', 'Software', 'Can the user change the layout of the system according to his needs and preferences?', '"In systems that use overlapping windows, is it easy for users to rearrange windows on the screen?"'),
	('Flexibility and efficiency of use', 'Software', 'Can the user change the system output according to his needs and preferences?', ''),
	('Flexibility and efficiency of use', 'Software', 'Can the user change the system output according to his needs and preferences?', 'Is the user able to select between different representation forms of information?'),
	('Flexibility and efficiency of use', 'Software', 'Can the user change the system output according to his needs and preferences?', 'Can the user control the speed in which the dialog is processed?'),
	('Flexibility and efficiency of use', 'Software', 'Can the user change the system output according to his needs and preferences?', 'Can the user control the speed of dynamic inputs and outputs?'),
	('Flexibility and efficiency of use', 'Software', 'Are appropriate input and output devices provided?', ''),
	('Flexibility and efficiency of use', 'Software', 'Are appropriate input and output devices provided?', 'Do the selected input device(s) match environmental constraints?'),
	('Flexibility and efficiency of use', 'Software', 'Are appropriate input and output devices provided?', 'Do the selected input device(s) match the task?'),
	('Flexibility and efficiency of use', 'Software', 'Are appropriate input and output devices provided?', '"If the system uses multiple input devices, has hand and eye movement between input devices been minimized?"'),
	('Flexibility and efficiency of use', 'Software', 'Does the system automate processes to increase efficiency?', ''),
	('Flexibility and efficiency of use', 'Software', 'Does the system automate processes to increase efficiency?', 'Does the system complete unambiguous partial input on a data entry field?'),
	('Flexibility and efficiency of use', 'Software', 'Does the system automate processes to increase efficiency?', '"When the user enters a screen or dialog box, is the cursor already positioned in the field users are most likely to need?"'),
	('Flexibility and efficiency of use', 'Software', 'Does the system automate processes to increase efficiency?', 'Is auto-fill avoided where there is more than one auto-fill option that matches?'),
	('Flexibility and efficiency of use', 'Hardware', 'Does the system provide shortcut functionality?', ''),
	('Flexibility and efficiency of use', 'Hardware', 'Does the system provide shortcut functionality?', 'Does the system provide shortcuts for the execution of the most frequently required functionality?'),
	('Flexibility and efficiency of use', 'Hardware', 'Does the system provide shortcut functionality?', 'Can the user define shortcuts by his own?'),
	('Flexibility and efficiency of use', 'Hardware', 'Can the user decide on using different input devices for performing the same action at each point in the dialog process?', ''),
	('Flexibility and efficiency of use', 'Hardware', 'Can the user decide on using different input devices for performing the same action at each point in the dialog process?', '"If menu lists are short (seven items or fewer), can users select an item by moving the cursor?"'),
	('Flexibility and efficiency of use', 'Hardware', 'Can the user decide on using different input devices for performing the same action at each point in the dialog process?', '"If the system uses a pointing device, do users have the option of either clicking on fields or using a keyboard shortcut?"'),
	('Flexibility and efficiency of use', 'Hardware', 'Can the user decide on using different input devices for performing the same action at each point in the dialog process?', '"In dialog boxes, do users have the option of either clicking directly on a dialog box option or using a keyboard shortcut?"'),
	('Flexibility and efficiency of use', 'Hardware', 'Can the user decide on using different input devices for performing the same action at each point in the dialog process?', '"Can expert users bypass nested dialog boxes with either type-ahead, user-defined macros, or keyboard shortcuts?"'),
	('Flexibility and efficiency of use', 'Hardware', 'Can the user decide on using different input devices for performing the same action at each point in the dialog process?', '"On data entry screens, do users have the option of either clicking directly on a field or using a keyboard shortcut?"'),
	('Flexibility and efficiency of use', 'Hardware', 'Can the user decide on using different input devices for performing the same action at each point in the dialog process?', '"On menus, do users have the option of either clicking directly on a menu item or using a keyboard shortcut?"'),
	('Flexibility and efficiency of use', 'Hardware', 'Can the user change the layout of the system according to his needs and preferences?', ''),
	('Flexibility and efficiency of use', 'Hardware', 'Can the user change the layout of the system according to his needs and preferences?', 'Is the size of graphics adaptable by the user?'),
	('Flexibility and efficiency of use', 'Hardware', 'Can the user change the layout of the system according to his needs and preferences?', 'Is the font size adaptable by the user for each UI element?'),
	('Flexibility and efficiency of use', 'Hardware', 'Can the user change the layout of the system according to his needs and preferences?', 'Are labels of objects and functions adaptable individually by the user?'),
	('Flexibility and efficiency of use', 'Hardware', 'Can the user change the layout of the system according to his needs and preferences?', '"In systems that use overlapping windows, is it easy for users to rearrange windows on the screen?"'),
	('Flexibility and efficiency of use', 'Hardware', 'Can the user change the system output according to his needs and preferences?', ''),
	('Flexibility and efficiency of use', 'Hardware', 'Can the user change the system output according to his needs and preferences?', 'Is the user able to select between different representation forms of information?'),
	('Flexibility and efficiency of use', 'Hardware', 'Can the user change the system output according to his needs and preferences?', 'Can the user control the speed in which the dialog is processed?'),
	('Flexibility and efficiency of use', 'Hardware', 'Can the user change the system output according to his needs and preferences?', 'Can the user control the speed of dynamic inputs and outputs?'),
	('Flexibility and efficiency of use', 'Hardware', 'Are appropriate input and output devices provided?', ''),
	('Flexibility and efficiency of use', 'Hardware', 'Are appropriate input and output devices provided?', 'Do the selected input device(s) match environmental constraints?'),
	('Flexibility and efficiency of use', 'Hardware', 'Are appropriate input and output devices provided?', 'Do the selected input device(s) match the task?'),
	('Flexibility and efficiency of use', 'Hardware', 'Are appropriate input and output devices provided?', '"If the system uses multiple input devices, has hand and eye movement between input devices been minimized?"'),
	('Flexibility and efficiency of use', 'Hardware', 'Does the system automate processes to increase efficiency?', ''),
	('Flexibility and efficiency of use', 'Hardware', 'Does the system automate processes to increase efficiency?', 'Does the system complete unambiguous partial input on a data entry field?'),
	('Flexibility and efficiency of use', 'Hardware', 'Does the system automate processes to increase efficiency?', '"When the user enters a screen or dialog box, is the cursor already positioned in the field users are most likely to need?"'),
	('Flexibility and efficiency of use', 'Hardware', 'Does the system automate processes to increase efficiency?', 'Is auto-fill avoided where there is more than one auto-fill option that matches?'),
	('Help and documentation', 'Software', 'Is the help solution oriented?', ''),
	('Help and documentation', 'Software', 'Is the help solution oriented?', 'Can the user get context sensitive help for each UI element?'),
	('Help and documentation', 'Software', 'Is the help solution oriented?', 'Is any help (on- and off-line) formulated in a step-based manner?'),
	('Help and documentation', 'Software', 'Is the help solution oriented?', '"Is the help system interface (navigation, presentation and conversation) consistent with the navigation, presentation and conversation interfaces of the application it supports?"'),
	('Help and documentation', 'Software', 'Is the help solution oriented?', 'Does the error message contain information about how the user can solve the error?'),
	('Help and documentation', 'Software', 'Is it easy to access and return from the help system?', ''),
	('Help and documentation', 'Software', 'Is it easy to access and return from the help system?', '"Is the help function visible; for example, a key labeled HELP or a special menu?"'),
	('Help and documentation', 'Software', 'Is it easy to access and return from the help system?', 'Can users resume work where they left off after accessing help?'),
	('Help and documentation', 'Hardware', 'Is the help solution oriented?', ''),
	('Help and documentation', 'Hardware', 'Is the help solution oriented?', 'Can the user get context sensitive help for each UI element?'),
	('Help and documentation', 'Hardware', 'Is the help solution oriented?', 'Is any help (on- and off-line) formulated in a step-based manner?'),
	('Help and documentation', 'Hardware', 'Is the help solution oriented?', '"Is the help system interface (navigation, presentation and conversation) consistent with the navigation, presentation and conversation interfaces of the application it supports?"'),
	('Help and documentation', 'Hardware', 'Is the help solution oriented?', 'Does the error message contain information about how the user can solve the error?'),
	('Help and documentation', 'Hardware', 'Is it easy to access and return from the help system?', ''),
	('Help and documentation', 'Hardware', 'Is it easy to access and return from the help system?', '"Is the help function visible; for example, a key labeled HELP or a special menu?"'),
	('Help and documentation', 'Hardware', 'Is it easy to access and return from the help system?', 'Can users resume work where they left off after accessing help?'),
	('"Help users recognize, diagnose, and recover from errors"', 'Software', 'Is the cause of the problem known?', ''),
	('"Help users recognize, diagnose, and recover from errors"', 'Software', 'Is the cause of the problem known?', 'Do error messages state the cause of the problem?'),
	('"Help users recognize, diagnose, and recover from errors"', 'Software', 'Is the cause of the problem known?', '"If pop-up windows are used to display error messages, do they allow the user to see the field in error?"'),
	('"Help users recognize, diagnose, and recover from errors"', 'Software', 'Is the cause of the problem known?', '"If an error is detected in a data entry field, does the system place the cursor in that field or highlight the error?"'),
	('"Help users recognize, diagnose, and recover from errors"', 'Hardware', 'Is the cause of the problem known?', ''),
	('"Help users recognize, diagnose, and recover from errors"', 'Hardware', 'Is the cause of the problem known?', 'Do error messages state the cause of the problem?'),
	('"Help users recognize, diagnose, and recover from errors"', 'Hardware', 'Is the cause of the problem known?', '"If pop-up windows are used to display error messages, do they allow the user to see the field in error?"'),
	('"Help users recognize, diagnose, and recover from errors"', 'Hardware', 'Is the cause of the problem known?', '"If an error is detected in a data entry field, does the system place the cursor in that field or highlight the error?"'),
	('Match between system and the real world', 'Software', 'Does the user need not to “translate” system messages to understand the system?', ''),
	('Match between system and the real world', 'Software', 'Does the user need not to “translate” system messages to understand the system?', 'Does the system use real-world metaphors?'),
	('Match between system and the real world', 'Software', 'Does the user need not to “translate” system messages to understand the system?', 'Do input and output correspond to real-world values?'),
	('Match between system and the real world', 'Software', 'Does the user need not to “translate” system messages to understand the system?', '"When prompts imply a necessary action, are the words in the message consistent with that action?"'),
	('Match between system and the real world', 'Software', 'Does the user need not to “translate” system messages to understand the system?', 'Do keystroke references in prompts match actual key names?'),
	('Match between system and the real world', 'Software', 'Does the user need not to “translate” system messages to understand the system?', '"On data entry screens, are tasks described in terminology familiar to users?"'),
	('Match between system and the real world', 'Software', 'Does the user need not to “translate” system messages to understand the system?', '"For question and answer interfaces, are questions stated in clear, simple language?"'),
	('Match between system and the real world', 'Software', 'Does the system provide comprehensive labels wherever possible?', ''),
	('Match between system and the real world', 'Software', 'Does the system provide comprehensive labels wherever possible?', '"Does each data entry screen have a short, simple, clear, distinctive title?"'),
	('Match between system and the real world', 'Software', 'Does the system provide comprehensive labels wherever possible?', '"Are field labels brief, familiar and descriptive?"'),
	('Match between system and the real world', 'Software', 'Does the system provide comprehensive labels wherever possible?', '"Are menu titles brief, yet long enough to communicate?"'),
	('Match between system and the real world', 'Software', 'Does the system provide comprehensive labels wherever possible?', 'Are field-level prompts provided for data entry screens?'),
	('Match between system and the real world', 'Software', 'Does the system automatically format information according to existing standards and conventions?', ''),
	('Match between system and the real world', 'Software', 'Does the system automatically format information according to existing standards and conventions?', 'Does the system automatically enter leading or trailing spaces to align decimal points?'),
	('Match between system and the real world', 'Software', 'Does the system automatically format information according to existing standards and conventions?', 'Does the system automatically enter commas in numeric values greater than 9999?'),
	('Match between system and the real world', 'Software', 'Does the system automatically format information according to existing standards and conventions?', 'Does the system automatically enter a currency sign and decimal for monetary entried?'),
	('Match between system and the real world', 'Hardware', 'Does the user need not to “translate” system messages to understand the system?', ''),
	('Match between system and the real world', 'Hardware', 'Does the user need not to “translate” system messages to understand the system?', 'Does the system use real-world metaphors?'),
	('Match between system and the real world', 'Hardware', 'Does the user need not to “translate” system messages to understand the system?', 'Do input and output correspond to real-world values?'),
	('Match between system and the real world', 'Hardware', 'Does the user need not to “translate” system messages to understand the system?', '"When prompts imply a necessary action, are the words in the message consistent with that action?"'),
	('Match between system and the real world', 'Hardware', 'Does the user need not to “translate” system messages to understand the system?', 'Do keystroke references in prompts match actual key names?'),
	('Match between system and the real world', 'Hardware', 'Does the user need not to “translate” system messages to understand the system?', '"On data entry screens, are tasks described in terminology familiar to users?"'),
	('Match between system and the real world', 'Hardware', 'Does the user need not to “translate” system messages to understand the system?', '"For question and answer interfaces, are questions stated in clear, simple language?"'),
	('Match between system and the real world', 'Hardware', 'Does the system provide comprehensive labels wherever possible?', ''),
	('Match between system and the real world', 'Hardware', 'Does the system provide comprehensive labels wherever possible?', '"Does each data entry screen have a short, simple, clear, distinctive title?"'),
	('Match between system and the real world', 'Hardware', 'Does the system provide comprehensive labels wherever possible?', '"Are field labels brief, familiar and descriptive?"'),
	('Match between system and the real world', 'Hardware', 'Does the system provide comprehensive labels wherever possible?', '"Are menu titles brief, yet long enough to communicate?"'),
	('Match between system and the real world', 'Hardware', 'Does the system provide comprehensive labels wherever possible?', 'Are field-level prompts provided for data entry screens?'),
	('Match between system and the real world', 'Hardware', 'Does the system automatically format information according to existing standards and conventions?', ''),
	('Match between system and the real world', 'Hardware', 'Does the system automatically format information according to existing standards and conventions?', 'Does the system automatically enter leading or trailing spaces to align decimal points?'),
	('Match between system and the real world', 'Hardware', 'Does the system automatically format information according to existing standards and conventions?', 'Does the system automatically enter commas in numeric values greater than 9999?'),
	('Match between system and the real world', 'Hardware', 'Does the system automatically format information according to existing standards and conventions?', 'Does the system automatically enter a currency sign and decimal for monetary entried?'),
	('Recognition rather than recall', 'Software', '"Does every UI element which is used multiple times during the system always have the same meaning, function and effect?"', ''),
	('Recognition rather than recall', 'Software', '"Does every UI element which is used multiple times during the system always have the same meaning, function and effect?"', 'Has the system been designed so that keys with similar names do not perform opposite (and potentially dangerous) actions?'),
	('Recognition rather than recall', 'Software', '"Does every UI element which is used multiple times during the system always have the same meaning, function and effect?"', '"If the system uses qualifier keys, are they used consistently throughout the system?"'),
	('Recognition rather than recall', 'Software', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', ''),
	('Recognition rather than recall', 'Software', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', '"Have prompts been formatted using white space, justification and visual cues for easy scanning?"'),
	('Recognition rather than recall', 'Software', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', '"Have zones been separated by spaces, lines, color, letters, bold titles, rules lines, or shaded areas?"'),
	('Recognition rather than recall', 'Software', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', '"Are field labels close to fields, but separated by at least one space?"'),
	('Recognition rather than recall', 'Software', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Are borders used to identify meaningful groups?'),
	('Recognition rather than recall', 'Software', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Is color coding consistent throughout the system?'),
	('Recognition rather than recall', 'Software', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Is color used in conjunction with some other redundant cue?'),
	('Recognition rather than recall', 'Software', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Is the first word of each menu choice the most important?'),
	('Recognition rather than recall', 'Software', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Are integers right-justified and real numbers decimal-aligned?'),
	('Recognition rather than recall', 'Software', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Are icons labeled?'),
	('Recognition rather than recall', 'Software', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Do field labels appear to the left of single fields and above list fields?'),
	('Recognition rather than recall', 'Software', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Does every display begin with a title or header that describes screen contents?'),
	('Recognition rather than recall', 'Software', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', '"Have items been grouped into logical zones, and have headings been used to distinguish between zones?"'),
	('Recognition rather than recall', 'Software', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Does each window have a title?'),
	('Recognition rather than recall', 'Software', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Is a legend provided if color codes are numerous or not obvious in meaning?'),
	('Recognition rather than recall', 'Software', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Is the most important information placed at the beginning of the prompt?'),
	('Recognition rather than recall', 'Software', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', '"If the system has multipage data entry screens, does each page have a sequential page number?"'),
	('Recognition rather than recall', 'Software', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Is the menu choice name on a higher-level menu used as the menu title of the lower-level menu?'),
	('Recognition rather than recall', 'Software', 'Does the user easiliy recognize which commands he can give on each screen?', ''),
	('Recognition rather than recall', 'Software', 'Does the user easiliy recognize which commands he can give on each screen?', 'Are inactive UI items grayed or omitted?'),
	('Recognition rather than recall', 'Software', 'Does the user easiliy recognize which commands he can give on each screen?', '"Do GUI menus offer affordance: that is, make obvious where selection is possible?"'),
	('Recognition rather than recall', 'Software', 'Does the user easiliy recognize which commands he can give on each screen?', 'Does the user immediately know the function and the effects of every UI element?'),
	('Recognition rather than recall', 'Software', 'Does the user easiliy recognize which commands he can give on each screen?', 'Are icons conrete and familiar?'),
	('Recognition rather than recall', 'Software', 'Does the system support the user in successfully achieving his task?', ''),
	('Recognition rather than recall', 'Software', 'Does the system support the user in successfully achieving his task?', 'Are there menu selection defaults?'),
	('Recognition rather than recall', 'Software', 'Does the system support the user in successfully achieving his task?', 'Are there salient visual cues to identify the active window?'),
	('Recognition rather than recall', 'Software', 'Does the system support the user in successfully achieving his task?', 'Does the menu structure match the task structure?'),
	('Recognition rather than recall', 'Software', 'Does the system support the user in successfully achieving his task?', '"Are high-value, high-chroma colors used to attract attention?"'),
	('Recognition rather than recall', 'Software', 'Does the system support the user in successfully achieving his task?', 'Is mandatory information marked?'),
	('Recognition rather than recall', 'Software', 'Does the system support the user in successfully achieving his task?', 'Do fields in data entry screens and dialog boxes contain default values when appropriate?'),
	('Recognition rather than recall', 'Software', 'Does the system support the user in successfully achieving his task?', '"For question and answer interfaces, are the valid inputs for a question listed?"'),
	('Recognition rather than recall', 'Hardware', '"Does every UI element which is used multiple times during the system always have the same meaning, function and effect?"', ''),
	('Recognition rather than recall', 'Hardware', '"Does every UI element which is used multiple times during the system always have the same meaning, function and effect?"', 'Has the system been designed so that keys with similar names do not perform opposite (and potentially dangerous) actions?'),
	('Recognition rather than recall', 'Hardware', '"Does every UI element which is used multiple times during the system always have the same meaning, function and effect?"', '"If the system uses qualifier keys, are they used consistently throughout the system?"'),
	('Recognition rather than recall', 'Hardware', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', ''),
	('Recognition rather than recall', 'Hardware', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', '"Have prompts been formatted using white space, justification and visual cues for easy scanning?"'),
	('Recognition rather than recall', 'Hardware', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', '"Have zones been separated by spaces, lines, color, letters, bold titles, rules lines, or shaded areas?"'),
	('Recognition rather than recall', 'Hardware', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', '"Are field labels close to fields, but separated by at least one space?"'),
	('Recognition rather than recall', 'Hardware', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Are borders used to identify meaningful groups?'),
	('Recognition rather than recall', 'Hardware', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Is color coding consistent throughout the system?'),
	('Recognition rather than recall', 'Hardware', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Is color used in conjunction with some other redundant cue?'),
	('Recognition rather than recall', 'Hardware', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Is the first word of each menu choice the most important?'),
	('Recognition rather than recall', 'Hardware', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Are integers right-justified and real numbers decimal-aligned?'),
	('Recognition rather than recall', 'Hardware', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Are icons labeled?'),
	('Recognition rather than recall', 'Hardware', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Do field labels appear to the left of single fields and above list fields?'),
	('Recognition rather than recall', 'Hardware', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Does every display begin with a title or header that describes screen contents?'),
	('Recognition rather than recall', 'Hardware', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', '"Have items been grouped into logical zones, and have headings been used to distinguish between zones?"'),
	('Recognition rather than recall', 'Hardware', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Does each window have a title?'),
	('Recognition rather than recall', 'Hardware', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Is a legend provided if color codes are numerous or not obvious in meaning?'),
	('Recognition rather than recall', 'Hardware', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Is the most important information placed at the beginning of the prompt?'),
	('Recognition rather than recall', 'Hardware', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', '"If the system has multipage data entry screens, does each page have a sequential page number?"'),
	('Recognition rather than recall', 'Hardware', 'Does the user easiliy recognize the screen layout and the meaning of single parts of the screen?', 'Is the menu choice name on a higher-level menu used as the menu title of the lower-level menu?'),
	('Recognition rather than recall', 'Hardware', 'Does the user easiliy recognize which commands he can give on each screen?', ''),
	('Recognition rather than recall', 'Hardware', 'Does the user easiliy recognize which commands he can give on each screen?', 'Are inactive UI items grayed or omitted?'),
	('Recognition rather than recall', 'Hardware', 'Does the user easiliy recognize which commands he can give on each screen?', '"Do GUI menus offer affordance: that is, make obvious where selection is possible?"'),
	('Recognition rather than recall', 'Hardware', 'Does the user easiliy recognize which commands he can give on each screen?', 'Does the user immediately know the function and the effects of every UI element?'),
	('Recognition rather than recall', 'Hardware', 'Does the user easiliy recognize which commands he can give on each screen?', 'Are icons conrete and familiar?'),
	('Recognition rather than recall', 'Hardware', 'Does the system support the user in successfully achieving his task?', ''),
	('Recognition rather than recall', 'Hardware', 'Does the system support the user in successfully achieving his task?', 'Are there menu selection defaults?'),
	('Recognition rather than recall', 'Hardware', 'Does the system support the user in successfully achieving his task?', 'Are there salient visual cues to identify the active window?'),
	('Recognition rather than recall', 'Hardware', 'Does the system support the user in successfully achieving his task?', 'Does the menu structure match the task structure?'),
	('Recognition rather than recall', 'Hardware', 'Does the system support the user in successfully achieving his task?', '"Are high-value, high-chroma colors used to attract attention?"'),
	('Recognition rather than recall', 'Hardware', 'Does the system support the user in successfully achieving his task?', 'Is mandatory information marked?'),
	('Recognition rather than recall', 'Hardware', 'Does the system support the user in successfully achieving his task?', 'Do fields in data entry screens and dialog boxes contain default values when appropriate?'),
	('Recognition rather than recall', 'Hardware', 'Does the system support the user in successfully achieving his task?', '"For question and answer interfaces, are the valid inputs for a question listed?"'),
	('User control and freedom', 'Software', 'Can the user control the dialog process?', ''),
	('User control and freedom', 'Software', 'Can the user control the dialog process?', 'Can the user re-do actions without having to rerun through the whole dialog process?'),
	('User control and freedom', 'Software', 'Can the user control the dialog process?', 'Does the system provide an undo-function for every user action?'),
	('User control and freedom', 'Software', 'Can the user control the dialog process?', '"If the system allows to undo user actions, is there a retracting mechanism to allow for multiple undos?"'),
	('User control and freedom', 'Software', 'Can the user control the dialog process?', 'Can the user cancel processes whenever he wants to?'),
	('User control and freedom', 'Software', 'Can the user control the dialog process?', 'Can the user reset the application?'),
	('User control and freedom', 'Software', 'Can the user control the dialog process?', '"If the system displays multiple windows, is navigation between windows simple and visible?"'),
	('User control and freedom', 'Software', 'Can the user control the dialog process?', '"If the system has multipage data entry screens, can users move backward and forward among the pages in the set?"'),
	('User control and freedom', 'Software', 'Can the user control the dialog process?', '"If the system uses a question and answer interface, can users go back to previous questions or skip forward to later questions?"'),
	('User control and freedom', 'Software', 'Can the user control the dialog process?', '"If the system has multiple menu levels, is there a mechanism that allows users to go back to previous menus?"'),
	('User control and freedom', 'Software', 'Can the user control the dialog process?', 'Can users move forward and backward between fields or dialog box options?'),
	('User control and freedom', 'Software', 'Can the user control the dialog process?', '"For data entry screens with many fields or in which source documents may be incomplete, can users save a partially filled screen?"'),
	('User control and freedom', 'Hardware', 'Can the user control the dialog process?', ''),
	('User control and freedom', 'Hardware', 'Can the user control the dialog process?', 'Can the user re-do actions without having to rerun through the whole dialog process?'),
	('User control and freedom', 'Hardware', 'Can the user control the dialog process?', 'Does the system provide an undo-function for every user action?'),
	('User control and freedom', 'Hardware', 'Can the user control the dialog process?', '"If the system allows to undo user actions, is there a retracting mechanism to allow for multiple undos?"'),
	('User control and freedom', 'Hardware', 'Can the user control the dialog process?', 'Can the user cancel processes whenever he wants to?'),
	('User control and freedom', 'Hardware', 'Can the user control the dialog process?', 'Can the user reset the application?'),
	('User control and freedom', 'Hardware', 'Can the user control the dialog process?', '"If the system displays multiple windows, is navigation between windows simple and visible?"'),
	('User control and freedom', 'Hardware', 'Can the user control the dialog process?', '"If the system has multipage data entry screens, can users move backward and forward among the pages in the set?"'),
	('User control and freedom', 'Hardware', 'Can the user control the dialog process?', '"If the system uses a question and answer interface, can users go back to previous questions or skip forward to later questions?"'),
	('User control and freedom', 'Hardware', 'Can the user control the dialog process?', '"If the system has multiple menu levels, is there a mechanism that allows users to go back to previous menus?"'),
	('User control and freedom', 'Hardware', 'Can the user control the dialog process?', 'Can users move forward and backward between fields or dialog box options?'),
	('User control and freedom', 'Hardware', 'Can the user control the dialog process?', '"For data entry screens with many fields or in which source documents may be incomplete, can users save a partially filled screen?"'),
	('Visibility of system status', 'Software', 'Is the user kept in the loop of what is going on?', ''),
	('Visibility of system status', 'Software', 'Is the user kept in the loop of what is going on?', 'Is the current status of an icon clearly indicated?'),
	('Visibility of system status', 'Software', 'Is the user kept in the loop of what is going on?', 'Do GUI menus make obvious when an item has been selected?'),
	('Visibility of system status', 'Software', 'Is the user kept in the loop of what is going on?', 'Do GUI menus make obvious whether deselection is possible?'),
	('Visibility of system status', 'Software', 'Is the user kept in the loop of what is going on?', '"In multipage data entry screens, is each page labeled to show its relation to others?"'),
	('Visibility of system status', 'Software', 'Is the user kept in the loop of what is going on?', '"If users must navigate between multiple screens, does the system use context labels, menu maps, and place markers as navigational aids?"'),
	('Visibility of system status', 'Software', 'Is every user action followed by a perceivable system feedback?', ''),
	('Visibility of system status', 'Software', 'Is every user action followed by a perceivable system feedback?', '"After the user completes an action (or group of actions), does the feedback indicate that the next group of actions can be started?"'),
	('Visibility of system status', 'Software', 'Is every user action followed by a perceivable system feedback?', 'Is there visual feedback in menus or dialog boxes about which choices are selectable?'),
	('Visibility of system status', 'Software', 'Is every user action followed by a perceivable system feedback?', 'Is there visual feedback in menus or dialog boxes about which choice the cursor is on now?'),
	('Visibility of system status', 'Software', 'Is every user action followed by a perceivable system feedback?', '"If multiple options can be selected in a menu or dialog box, is there visual feedback about which options are already selected?"'),
	('Visibility of system status', 'Software', 'Is every user action followed by a perceivable system feedback?', 'Is there visual feedback when objects are selected or moved?'),
	('Visibility of system status', 'Hardware', 'Is the user kept in the loop of what is going on?', ''),
	('Visibility of system status', 'Hardware', 'Is the user kept in the loop of what is going on?', 'Is the current status of an icon clearly indicated?'),
	('Visibility of system status', 'Hardware', 'Is the user kept in the loop of what is going on?', 'Do GUI menus make obvious when an item has been selected?'),
	('Visibility of system status', 'Hardware', 'Is the user kept in the loop of what is going on?', 'Do GUI menus make obvious whether deselection is possible?'),
	('Visibility of system status', 'Hardware', 'Is the user kept in the loop of what is going on?', '"In multipage data entry screens, is each page labeled to show its relation to others?"'),
	('Visibility of system status', 'Hardware', 'Is the user kept in the loop of what is going on?', '"If users must navigate between multiple screens, does the system use context labels, menu maps, and place markers as navigational aids?"'),
	('Visibility of system status', 'Hardware', 'Is every user action followed by a perceivable system feedback?', ''),
	('Visibility of system status', 'Hardware', 'Is every user action followed by a perceivable system feedback?', '"After the user completes an action (or group of actions), does the feedback indicate that the next group of actions can be started?"'),
	('Visibility of system status', 'Hardware', 'Is every user action followed by a perceivable system feedback?', 'Is there visual feedback in menus or dialog boxes about which choices are selectable?'),
	('Visibility of system status', 'Hardware', 'Is every user action followed by a perceivable system feedback?', 'Is there visual feedback in menus or dialog boxes about which choice the cursor is on now?'),
	('Visibility of system status', 'Hardware', 'Is every user action followed by a perceivable system feedback?', '"If multiple options can be selected in a menu or dialog box, is there visual feedback about which options are already selected?"'),
	('Visibility of system status', 'Hardware', 'Is every user action followed by a perceivable system feedback?', 'Is there visual feedback when objects are selected or moved?'),
	('Privacy & Security', 'Software', 'Are protected areas completely inaccessible?', ''),
	('Privacy & Security', 'Software', 'Can protected or confidential areas be accessed with a certain password?', ''),
	('Privacy & Security', 'Hardware', 'Are protected areas completely inaccessible?', ''),
	('Privacy & Security', 'Hardware', 'Can protected or confidential areas be accessed with a certain password?', '');

INSERT INTO questionnaire (creator, title) VALUES
	('Daniel Scherer', 'Questionario teste');

INSERT INTO questionnaire_question(questionnaire_id, question_id) VALUES
    (1, 1),
    (1, 2),
    (1, 3),
    (1, 4),
    (1, 5),
    (1, 6),
    (1, 7),
    (1, 8),
    (1, 9),
    (1, 10)
