/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.uepb.lufh.avalia.contract.api;

import com.uepb.lufh.avalia.contract.model.Report;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-02-22T00:56:03.914173-03:00[America/Fortaleza]")
@Validated
@Api(value = "reports", description = "the reports API")
public interface ReportsApi {

    default ReportsApiDelegate getDelegate() {
        return new ReportsApiDelegate() {};
    }

    /**
     * POST /reports : Add a new report
     *
     * @param report  (required)
     * @return Internal server error (status code 500)
     */

    @ApiOperation(value = "Add a new report", nickname = "createReport", notes = "", tags={ "reports", })
    @ApiResponses(value = { 

        @ApiResponse(code = 500, message = "Internal server error") })
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/reports",
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> createReport(

@ApiParam(value = "", required = true )   @Valid @RequestBody Report report) {
        return getDelegate().createReport(report);
    }


    /**
     * DELETE /reports/{report_id} : Deletes a report
     *
     * @param reportId Report id to delete (required)
     * @return Invalid ID supplied (status code 400)
     *         or Report not found (status code 404)
     */

    @ApiOperation(value = "Deletes a report", nickname = "deleteReport", notes = "", tags={ "reports", })
    @ApiResponses(value = { 

        @ApiResponse(code = 400, message = "Invalid ID supplied"),

        @ApiResponse(code = 404, message = "Report not found") })
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/reports/{report_id}"
    )
    default ResponseEntity<Void> deleteReport(@ApiParam(value = "Report id to delete", required = true) @PathVariable("report_id") Long reportId

) {
        return getDelegate().deleteReport(reportId);
    }


    /**
     * GET /reports/{report_id} : Find a report by ID
     *
     * @param reportId ID of report to return (required)
     * @return successful operation (status code 200)
     *         or Invalid ID supplied (status code 400)
     *         or Report not found (status code 404)
     */

    @ApiOperation(value = "Find a report by ID", nickname = "findReport", notes = "", response = Report.class, tags={ "reports", })
    @ApiResponses(value = { 

        @ApiResponse(code = 200, message = "successful operation", response = Report.class),

        @ApiResponse(code = 400, message = "Invalid ID supplied"),

        @ApiResponse(code = 404, message = "Report not found") })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/reports/{report_id}",
        produces = { "application/json", "application/xml" }
    )
    default ResponseEntity<Report> findReport(@ApiParam(value = "ID of report to return", required = true) @PathVariable("report_id") Long reportId

) {
        return getDelegate().findReport(reportId);
    }


    /**
     * GET /reports : Finds all reports
     *
     * @param requestEvaluationId Request evaluation id values that can be considered for filter (optional)
     * @param productType Product type values that can be considered for filter (optional)
     * @param reportDate Report date values that can be considered for filter (optional)
     * @return successful operation (status code 200)
     *         or Not found (status code 404)
     */

    @ApiOperation(value = "Finds all reports", nickname = "findReports", notes = "", response = Report.class, responseContainer = "List", tags={ "reports", })
    @ApiResponses(value = { 

        @ApiResponse(code = 200, message = "successful operation", response = Report.class, responseContainer = "List"),

        @ApiResponse(code = 404, message = "Not found") })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/reports",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Report>> findReports(@ApiParam(value = "Request evaluation id values that can be considered for filter") @Valid @RequestParam(value = "request_evaluation_id", required = false) String requestEvaluationId

,@ApiParam(value = "Product type values that can be considered for filter", allowableValues = "Software, Hardware, Hardware/Software") @Valid @RequestParam(value = "product_type", required = false) String productType

,@ApiParam(value = "Report date values that can be considered for filter") @Valid @RequestParam(value = "report_date", required = false) String reportDate

) {
        return getDelegate().findReports(requestEvaluationId, productType, reportDate);
    }


    /**
     * PUT /reports/{report_id} : Update an existing report
     *
     * @param reportId Report id to update (required)
     * @param report  (required)
     * @return Invalid ID supplied (status code 400)
     *         or Question not found (status code 404)
     *         or Validation exception (status code 405)
     */

    @ApiOperation(value = "Update an existing report", nickname = "updateReport", notes = "", tags={ "reports", })
    @ApiResponses(value = { 

        @ApiResponse(code = 400, message = "Invalid ID supplied"),

        @ApiResponse(code = 404, message = "Question not found"),

        @ApiResponse(code = 405, message = "Validation exception") })
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/reports/{report_id}",
        consumes = { "application/json", "application/xml" }
    )
    default ResponseEntity<Void> updateReport(@ApiParam(value = "Report id to update", required = true) @PathVariable("report_id") Long reportId

,

@ApiParam(value = "", required = true )   @Valid @RequestBody Report report) {
        return getDelegate().updateReport(reportId, report);
    }

}
