/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package contract;

import model.QuestionnaireDto;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;
import springfox.documentation.annotations.ApiIgnore;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-02-21T22:46:02.357514-03:00[America/Fortaleza]")
@Validated
@Api(value = "questionnaires", description = "the questionnaires API")
public interface QuestionnairesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /questionnaires : Add a new questionnaire
     *
     * @param questionnaireDto  (optional)
     * @return Internal server error (status code 500)
     */
    @ApiOperation(value = "Add a new questionnaire", nickname = "createQuestionaire", notes = "", tags={ "questionnaires", })
    @ApiResponses(value = { 
        @ApiResponse(code = 500, message = "Internal server error") })
    @PostMapping(
        value = "/questionnaires",
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> _createQuestionaire(@ApiParam(value = ""  )  @Valid @RequestBody(required = false) QuestionnaireDto questionnaireDto) {
        return createQuestionaire(questionnaireDto);
    }

    // Override this method
    default  ResponseEntity<Void> createQuestionaire(QuestionnaireDto questionnaireDto) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /questionnaires/{questionnaire_id} : Deletes a questionnaire
     *
     * @param questionnaireId Questionnaire id to delete (required)
     * @return Invalid ID supplied (status code 400)
     *         or Questionnaire not found (status code 404)
     */
    @ApiOperation(value = "Deletes a questionnaire", nickname = "deleteQuestionnaire", notes = "", tags={ "questionnaires", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Questionnaire not found") })
    @DeleteMapping(
        value = "/questionnaires/{questionnaire_id}"
    )
    default ResponseEntity<Void> _deleteQuestionnaire(@ApiParam(value = "Questionnaire id to delete",required=true) @PathVariable("questionnaire_id") Long questionnaireId) {
        return deleteQuestionnaire(questionnaireId);
    }

    // Override this method
    default  ResponseEntity<Void> deleteQuestionnaire(Long questionnaireId) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /questionnaires/{questionnaire_id} : Find questionnaire by ID
     *
     * @param questionnaireId ID of questionnaire to return (required)
     * @return successful operation (status code 200)
     *         or Invalid ID supplied (status code 400)
     *         or Questionnaire not found (status code 404)
     */
    @ApiOperation(value = "Find questionnaire by ID", nickname = "findQuestionnaire", notes = "", response = QuestionnaireDto.class, tags={ "questionnaires", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = QuestionnaireDto.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Questionnaire not found") })
    @GetMapping(
        value = "/questionnaires/{questionnaire_id}",
        produces = { "application/json", "application/xml" }
    )
    default ResponseEntity<QuestionnaireDto> _findQuestionnaire(@ApiParam(value = "ID of questionnaire to return",required=true) @PathVariable("questionnaire_id") Long questionnaireId) {
        return findQuestionnaire(questionnaireId);
    }

    // Override this method
    default  ResponseEntity<QuestionnaireDto> findQuestionnaire(Long questionnaireId) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"creator\" : \"creator\", \"questions\" : [ { \"reference\" : { \"bibliography\" : \"bibliography\", \"type\" : \"Article\" }, \"baseQuestion\" : \"Is it designed minimal?\", \"answer\" : { \"severity\" : \"0 Not a usability problem at all\", \"weight\" : \"0 Necessary for every System\", \"possibleAnswers\" : [ \"possibleAnswers\", \"possibleAnswers\" ], \"choosenAnswer\" : \"choosenAnswer\" }, \"id\" : 0, \"detailedQuestion\" : \"Is only (and all) information, essential to decision making, displayed on the screen?\", \"class\" : { \"name\" : \"Aesthetic and minimalist design\" }, \"productType\" : \"Software\" }, { \"reference\" : { \"bibliography\" : \"bibliography\", \"type\" : \"Article\" }, \"baseQuestion\" : \"Is it designed minimal?\", \"answer\" : { \"severity\" : \"0 Not a usability problem at all\", \"weight\" : \"0 Necessary for every System\", \"possibleAnswers\" : [ \"possibleAnswers\", \"possibleAnswers\" ], \"choosenAnswer\" : \"choosenAnswer\" }, \"id\" : 0, \"detailedQuestion\" : \"Is only (and all) information, essential to decision making, displayed on the screen?\", \"class\" : { \"name\" : \"Aesthetic and minimalist design\" }, \"productType\" : \"Software\" } ], \"id\" : 0, \"evaluator\" : \"evaluator\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/xml"))) {
                    String exampleString = "<Questionnaire> <id>123456789</id> <evaluator>aeiou</evaluator> <creator>aeiou</creator> </Questionnaire>";
                    ApiUtil.setExampleResponse(request, "application/xml", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /questionnaires : Finds all questionnaires
     *
     * @param evaluator Evaluator values that can be considered for filter (optional)
     * @param creator Creator values that can be considered for filter (optional)
     * @return successful operation (status code 200)
     *         or Not found (status code 404)
     */
    @ApiOperation(value = "Finds all questionnaires", nickname = "findQuestionnaires", notes = "", response = QuestionnaireDto.class, responseContainer = "List", tags={ "questionnaires", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = QuestionnaireDto.class, responseContainer = "List"),
        @ApiResponse(code = 404, message = "Not found") })
    @GetMapping(
        value = "/questionnaires",
        produces = { "application/json" }
    )
    default ResponseEntity<List<QuestionnaireDto>> _findQuestionnaires(@ApiParam(value = "Evaluator values that can be considered for filter") @Valid @RequestParam(value = "evaluator", required = false) String evaluator,@ApiParam(value = "Creator values that can be considered for filter") @Valid @RequestParam(value = "creator", required = false) String creator) {
        return findQuestionnaires(evaluator, creator);
    }

    // Override this method
    default  ResponseEntity<List<QuestionnaireDto>> findQuestionnaires(String evaluator, String creator) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"creator\" : \"creator\", \"questions\" : [ { \"reference\" : { \"bibliography\" : \"bibliography\", \"type\" : \"Article\" }, \"baseQuestion\" : \"Is it designed minimal?\", \"answer\" : { \"severity\" : \"0 Not a usability problem at all\", \"weight\" : \"0 Necessary for every System\", \"possibleAnswers\" : [ \"possibleAnswers\", \"possibleAnswers\" ], \"choosenAnswer\" : \"choosenAnswer\" }, \"id\" : 0, \"detailedQuestion\" : \"Is only (and all) information, essential to decision making, displayed on the screen?\", \"class\" : { \"name\" : \"Aesthetic and minimalist design\" }, \"productType\" : \"Software\" }, { \"reference\" : { \"bibliography\" : \"bibliography\", \"type\" : \"Article\" }, \"baseQuestion\" : \"Is it designed minimal?\", \"answer\" : { \"severity\" : \"0 Not a usability problem at all\", \"weight\" : \"0 Necessary for every System\", \"possibleAnswers\" : [ \"possibleAnswers\", \"possibleAnswers\" ], \"choosenAnswer\" : \"choosenAnswer\" }, \"id\" : 0, \"detailedQuestion\" : \"Is only (and all) information, essential to decision making, displayed on the screen?\", \"class\" : { \"name\" : \"Aesthetic and minimalist design\" }, \"productType\" : \"Software\" } ], \"id\" : 0, \"evaluator\" : \"evaluator\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /questionnaires/{questionnaire_id} : Update an existing questionnaire
     *
     * @param questionnaireId Questionnaire id to update (required)
     * @param questionnaireDto  (required)
     * @return Invalid ID supplied (status code 400)
     *         or Questionnaire not found (status code 404)
     *         or Validation exception (status code 405)
     */
    @ApiOperation(value = "Update an existing questionnaire", nickname = "updateQuestionnaire", notes = "", tags={ "questionnaires", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Questionnaire not found"),
        @ApiResponse(code = 405, message = "Validation exception") })
    @PutMapping(
        value = "/questionnaires/{questionnaire_id}",
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> _updateQuestionnaire(@ApiParam(value = "Questionnaire id to update",required=true) @PathVariable("questionnaire_id") Long questionnaireId,@ApiParam(value = "" ,required=true )  @Valid @RequestBody QuestionnaireDto questionnaireDto) {
        return updateQuestionnaire(questionnaireId, questionnaireDto);
    }

    // Override this method
    default  ResponseEntity<Void> updateQuestionnaire(Long questionnaireId, QuestionnaireDto questionnaireDto) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
