/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package contract;

import model.QuestionDto;
import model.RequestEvaluationDto;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;
import springfox.documentation.annotations.ApiIgnore;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-02-21T22:46:02.357514-03:00[America/Fortaleza]")
@Validated
@Api(value = "request-evaluations", description = "the request-evaluations API")
public interface RequestEvaluationsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /request-evaluations : Add a new request-evaluation
     *
     * @param questionDto Question object that needs to be added to the form (required)
     * @return Internal server error (status code 500)
     */
    @ApiOperation(value = "Add a new request-evaluation", nickname = "createRequestEvaluation", notes = "", tags={ "request-evaluations", })
    @ApiResponses(value = { 
        @ApiResponse(code = 500, message = "Internal server error") })
    @PostMapping(
        value = "/request-evaluations",
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> _createRequestEvaluation(@ApiParam(value = "Question object that needs to be added to the form" ,required=true )  @Valid @RequestBody QuestionDto questionDto) {
        return createRequestEvaluation(questionDto);
    }

    // Override this method
    default  ResponseEntity<Void> createRequestEvaluation(QuestionDto questionDto) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /request-evaluations/{request_evaluation_id} : Deletes a request evaluation
     *
     * @param requestEvaluationId Request Evaluation id to delete (required)
     * @return Invalid ID supplied (status code 400)
     *         or Request Evaluation not found (status code 404)
     */
    @ApiOperation(value = "Deletes a request evaluation", nickname = "deleteRequestEvaluation", notes = "", tags={ "request-evaluations", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Request Evaluation not found") })
    @DeleteMapping(
        value = "/request-evaluations/{request_evaluation_id}"
    )
    default ResponseEntity<Void> _deleteRequestEvaluation(@ApiParam(value = "Request Evaluation id to delete",required=true) @PathVariable("request_evaluation_id") Long requestEvaluationId) {
        return deleteRequestEvaluation(requestEvaluationId);
    }

    // Override this method
    default  ResponseEntity<Void> deleteRequestEvaluation(Long requestEvaluationId) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /request-evaluations/{request_evaluation_id} : Find request evaluation by ID
     *
     * @param requestEvaluationId ID of request evaluation to return (required)
     * @return successful operation (status code 200)
     *         or Invalid ID supplied (status code 400)
     *         or Request evaluation not found (status code 404)
     */
    @ApiOperation(value = "Find request evaluation by ID", nickname = "findRequestEvaluation", notes = "", response = RequestEvaluationDto.class, tags={ "request-evaluations", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = RequestEvaluationDto.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Request evaluation not found") })
    @GetMapping(
        value = "/request-evaluations/{request_evaluation_id}",
        produces = { "application/json", "application/xml" }
    )
    default ResponseEntity<RequestEvaluationDto> _findRequestEvaluation(@ApiParam(value = "ID of request evaluation to return",required=true) @PathVariable("request_evaluation_id") Long requestEvaluationId) {
        return findRequestEvaluation(requestEvaluationId);
    }

    // Override this method
    default  ResponseEntity<RequestEvaluationDto> findRequestEvaluation(Long requestEvaluationId) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"coverage\" : \"coverage\", \"productId\" : \"productId\", \"customerCpfCnpj\" : \"customerCpfCnpj\", \"endDate\" : \"2000-01-23T04:56:07.000+00:00\", \"urgency\" : true, \"testType\" : \"compliance inspection\", \"id\" : 0, \"startDate\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/xml"))) {
                    String exampleString = "<null> <id>123456789</id> <productId>aeiou</productId> <customerCpfCnpj>aeiou</customerCpfCnpj> <startDate>2000-01-23T04:56:07.000Z</startDate> <endDate>2000-01-23T04:56:07.000Z</endDate> <urgency>true</urgency> <testType>aeiou</testType> <coverage>aeiou</coverage> </null>";
                    ApiUtil.setExampleResponse(request, "application/xml", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /request-evaluations : Finds all request-evaluations
     *
     * @param customerCpfCnpj CPF and CNPJ values that can be considered for filter (optional)
     * @return successful operation (status code 200)
     *         or Not found (status code 404)
     */
    @ApiOperation(value = "Finds all request-evaluations", nickname = "findRequestEvaluations", notes = "", response = RequestEvaluationDto.class, responseContainer = "List", tags={ "request-evaluations", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = RequestEvaluationDto.class, responseContainer = "List"),
        @ApiResponse(code = 404, message = "Not found") })
    @GetMapping(
        value = "/request-evaluations",
        produces = { "application/json" }
    )
    default ResponseEntity<List<RequestEvaluationDto>> _findRequestEvaluations(@ApiParam(value = "CPF and CNPJ values that can be considered for filter") @Valid @RequestParam(value = "customer_cpf_cnpj", required = false) String customerCpfCnpj) {
        return findRequestEvaluations(customerCpfCnpj);
    }

    // Override this method
    default  ResponseEntity<List<RequestEvaluationDto>> findRequestEvaluations(String customerCpfCnpj) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"coverage\" : \"coverage\", \"productId\" : \"productId\", \"customerCpfCnpj\" : \"customerCpfCnpj\", \"endDate\" : \"2000-01-23T04:56:07.000+00:00\", \"urgency\" : true, \"testType\" : \"compliance inspection\", \"id\" : 0, \"startDate\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /request-evaluations/{request_evaluation_id} : Update an existing request evaluation
     *
     * @param requestEvaluationId Request Evaluation id to update (required)
     * @param requestEvaluationDto  (required)
     * @return Invalid ID supplied (status code 400)
     *         or Request Evaluation not found (status code 404)
     *         or Validation exception (status code 405)
     */
    @ApiOperation(value = "Update an existing request evaluation", nickname = "updateRequestEvaluation", notes = "", tags={ "request-evaluations", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Request Evaluation not found"),
        @ApiResponse(code = 405, message = "Validation exception") })
    @PutMapping(
        value = "/request-evaluations/{request_evaluation_id}",
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> _updateRequestEvaluation(@ApiParam(value = "Request Evaluation id to update",required=true) @PathVariable("request_evaluation_id") Long requestEvaluationId,@ApiParam(value = "" ,required=true )  @Valid @RequestBody RequestEvaluationDto requestEvaluationDto) {
        return updateRequestEvaluation(requestEvaluationId, requestEvaluationDto);
    }

    // Override this method
    default  ResponseEntity<Void> updateRequestEvaluation(Long requestEvaluationId, RequestEvaluationDto requestEvaluationDto) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
