/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.uepb.lufh.avalia.entrypoint.contract.api;

import com.uepb.lufh.avalia.entrypoint.contract.model.Questionnaire;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import javax.validation.Valid;
import java.util.List;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-02-22T02:43:06.822926-03:00[America/Fortaleza]")
@Validated
@Api(value = "questionnaires", description = "the questionnaires API")
public interface QuestionnairesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /questionnaires : Add a new questionnaire
     *
     * @param questionnaire  (optional)
     * @return Internal server error (status code 500)
     */

    @ApiOperation(value = "Add a new questionnaire", nickname = "createQuestionaire", notes = "", tags={ "questionnaires", })
    @ApiResponses(value = { 

        @ApiResponse(code = 500, message = "Internal server error") })
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/questionnaires",
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> createQuestionaire(

@ApiParam(value = "" )   @Valid @RequestBody(required = false) Questionnaire questionnaire) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /questionnaires/{questionnaire_id} : Deletes a questionnaire
     *
     * @param questionnaireId Questionnaire id to delete (required)
     * @return Invalid ID supplied (status code 400)
     *         or Questionnaire not found (status code 404)
     */

    @ApiOperation(value = "Deletes a questionnaire", nickname = "deleteQuestionnaire", notes = "", tags={ "questionnaires", })
    @ApiResponses(value = { 

        @ApiResponse(code = 400, message = "Invalid ID supplied"),

        @ApiResponse(code = 404, message = "Questionnaire not found") })
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/questionnaires/{questionnaire_id}"
    )
    default ResponseEntity<Void> deleteQuestionnaire(@ApiParam(value = "Questionnaire id to delete", required = true) @PathVariable("questionnaire_id") Long questionnaireId

) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /questionnaires/{questionnaire_id} : Find questionnaire by ID
     *
     * @param questionnaireId ID of questionnaire to return (required)
     * @return successful operation (status code 200)
     *         or Invalid ID supplied (status code 400)
     *         or Questionnaire not found (status code 404)
     */

    @ApiOperation(value = "Find questionnaire by ID", nickname = "findQuestionnaire", notes = "", response = Questionnaire.class, tags={ "questionnaires", })
    @ApiResponses(value = { 

        @ApiResponse(code = 200, message = "successful operation", response = Questionnaire.class),

        @ApiResponse(code = 400, message = "Invalid ID supplied"),

        @ApiResponse(code = 404, message = "Questionnaire not found") })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/questionnaires/{questionnaire_id}",
        produces = { "application/json", "application/xml" }
    )
    default ResponseEntity<Questionnaire> findQuestionnaire(@ApiParam(value = "ID of questionnaire to return", required = true) @PathVariable("questionnaire_id") Long questionnaireId

) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"creator\" : \"creator\", \"questions\" : [ { \"reference\" : { \"bibliography\" : \"bibliography\", \"type\" : \"Article\" }, \"baseQuestion\" : \"Is it designed minimal?\", \"answer\" : { \"severity\" : \"0 Not a usability problem at all\", \"weight\" : \"0 Necessary for every System\", \"possibleAnswers\" : [ \"possibleAnswers\", \"possibleAnswers\" ], \"choosenAnswer\" : \"choosenAnswer\" }, \"id\" : 0, \"detailedQuestion\" : \"Is only (and all) information, essential to decision making, displayed on the screen?\", \"class\" : { \"name\" : \"Aesthetic and minimalist design\" }, \"productType\" : \"Software\" }, { \"reference\" : { \"bibliography\" : \"bibliography\", \"type\" : \"Article\" }, \"baseQuestion\" : \"Is it designed minimal?\", \"answer\" : { \"severity\" : \"0 Not a usability problem at all\", \"weight\" : \"0 Necessary for every System\", \"possibleAnswers\" : [ \"possibleAnswers\", \"possibleAnswers\" ], \"choosenAnswer\" : \"choosenAnswer\" }, \"id\" : 0, \"detailedQuestion\" : \"Is only (and all) information, essential to decision making, displayed on the screen?\", \"class\" : { \"name\" : \"Aesthetic and minimalist design\" }, \"productType\" : \"Software\" } ], \"id\" : 0, \"evaluator\" : \"evaluator\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/xml"))) {
                    String exampleString = "<Questionnaire> <id>123456789</id> <evaluator>aeiou</evaluator> <creator>aeiou</creator> </Questionnaire>";
                    ApiUtil.setExampleResponse(request, "application/xml", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /questionnaires : Finds all questionnaires
     *
     * @param evaluator Evaluator values that can be considered for filter (optional)
     * @param creator Creator values that can be considered for filter (optional)
     * @return successful operation (status code 200)
     *         or Not found (status code 404)
     */

    @ApiOperation(value = "Finds all questionnaires", nickname = "findQuestionnaires", notes = "", response = Questionnaire.class, responseContainer = "List", tags={ "questionnaires", })
    @ApiResponses(value = { 

        @ApiResponse(code = 200, message = "successful operation", response = Questionnaire.class, responseContainer = "List"),

        @ApiResponse(code = 404, message = "Not found") })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/questionnaires",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Questionnaire>> findQuestionnaires(@ApiParam(value = "Evaluator values that can be considered for filter") @Valid @RequestParam(value = "evaluator", required = false) String evaluator

,@ApiParam(value = "Creator values that can be considered for filter") @Valid @RequestParam(value = "creator", required = false) String creator

) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"creator\" : \"creator\", \"questions\" : [ { \"reference\" : { \"bibliography\" : \"bibliography\", \"type\" : \"Article\" }, \"baseQuestion\" : \"Is it designed minimal?\", \"answer\" : { \"severity\" : \"0 Not a usability problem at all\", \"weight\" : \"0 Necessary for every System\", \"possibleAnswers\" : [ \"possibleAnswers\", \"possibleAnswers\" ], \"choosenAnswer\" : \"choosenAnswer\" }, \"id\" : 0, \"detailedQuestion\" : \"Is only (and all) information, essential to decision making, displayed on the screen?\", \"class\" : { \"name\" : \"Aesthetic and minimalist design\" }, \"productType\" : \"Software\" }, { \"reference\" : { \"bibliography\" : \"bibliography\", \"type\" : \"Article\" }, \"baseQuestion\" : \"Is it designed minimal?\", \"answer\" : { \"severity\" : \"0 Not a usability problem at all\", \"weight\" : \"0 Necessary for every System\", \"possibleAnswers\" : [ \"possibleAnswers\", \"possibleAnswers\" ], \"choosenAnswer\" : \"choosenAnswer\" }, \"id\" : 0, \"detailedQuestion\" : \"Is only (and all) information, essential to decision making, displayed on the screen?\", \"class\" : { \"name\" : \"Aesthetic and minimalist design\" }, \"productType\" : \"Software\" } ], \"id\" : 0, \"evaluator\" : \"evaluator\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /questionnaires/{questionnaire_id} : Update an existing questionnaire
     *
     * @param questionnaireId Questionnaire id to update (required)
     * @param questionnaire  (required)
     * @return Invalid ID supplied (status code 400)
     *         or Questionnaire not found (status code 404)
     *         or Validation exception (status code 405)
     */

    @ApiOperation(value = "Update an existing questionnaire", nickname = "updateQuestionnaire", notes = "", tags={ "questionnaires", })
    @ApiResponses(value = { 

        @ApiResponse(code = 400, message = "Invalid ID supplied"),

        @ApiResponse(code = 404, message = "Questionnaire not found"),

        @ApiResponse(code = 405, message = "Validation exception") })
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/questionnaires/{questionnaire_id}",
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> updateQuestionnaire(@ApiParam(value = "Questionnaire id to update", required = true) @PathVariable("questionnaire_id") Long questionnaireId

,

@ApiParam(value = "", required = true )   @Valid @RequestBody Questionnaire questionnaire) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
